article/urls.py
#引入path
from django.urls import path

# 引入 views.py
from . import views

# 部署应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('article-list/',views.article_list,name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    # 写文章
    path('article-create/',views.article_create,name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path
# 引入include
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    #新增代码，配置app的url
    path('article/',include('article.urls',namespace='article')),
]

article/models.py
from django.db import models

# Create your models here.
# 导入内建的User模型
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务
from django.utils import timezone

class ArticlePost(models.Model):
    # 文章作者，参数 on_delete 用于指定数据删除的方式
    auther = models.ForeignKey(User,on_delete=models.CASCADE)

    # 文章标题，models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文，保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间，参数default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间，参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # 内部类 class Meta 用于给model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # -created 表明数据应该以倒序排列
        ordering = ('-created',)

    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title','body')

article/views.py
from django.shortcuts import render

# Create your views here.

# 导入 HttpResponse 模块
from django.http import HttpResponse
from django.shortcuts import render

# 导入数据模型 ArticlePost
from .models import ArticlePost
import markdown

# 引入redirect重定向模块
from django.shortcuts import render,redirect
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
# 引入User模型
from django.contrib.auth.models import User


# 视图函数
def article_list(request):
    #return HttpResponse("Hello World!")
    # 取出所有博客文章
    articles = ArticlePost.objects.all()
    #需要传递给模板(templates)的对象
    context = { 'articles': articles}
    # render函数 载入模板 并返回context对象
    return render(request,'article/list.html',context)


# 文章详情
def article_detail(request,id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)
 
   # 将markdown 语法渲染成html样式
    article.body = markdown.markdown(article.body,
    extensions=[
    # 包含 缩写 表格等常用扩展
    'markdown.extensions.extra',
    # 语法高亮扩展
    'markdown.extensions.codehilite',
    ])

    # 需要传递给模板的对象
    context = {'article': article }
    # 载入模板，并返回context对象
    return render(request,'article/detail.html',context)


# 写文章的视图
def article_create(request):
    #判断用户是否提交数据
    if request.method == 'POST':
        #将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_article.author = User.objects.get(id=1)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form }
        # 返回模板
        return render(request,'article/create.html',context)


# 删文章
def article_delete(request,id):
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect("article:article_list")


## 安全删除文章
def article_safe_delete(request,id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

templates/article/create.html
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入base.html中定义的title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入base.html 中定义的content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
  <div class="row">
    <div class="col-12">
      <br>
      <!-- 提交文章的表单 -->
      <form method="post" action=".">
        <!-- Django中需要POST数据的地方都必须有csrf_token -->
        {% csrf_token %}
        <div class="form-group">
          <!-- 标签 -->
          <label for="title">文章标题</label>
          <!-- 文本框 -->
          <input type="text" class="form-control" id="title" name="title">
        </div>
        <!-- 文章正文 -->
        <div class="form-group">
          <label for="body">文章正文</label>
          <!-- 文本区域 -->
          <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
        </div>
        <!-- 提交按钮 -->
        <button type="submit" class="btn btn-primary">完成</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入base.html 中定义的 title-->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入base.html 中定义的 content-->
{% block content %}

<!-- 文章详情 -->
<div class="container">
  <div class="row">
    <!-- 标题及作者 -->
    <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
    <div class="col-12 alert alert-success">作者：{{ article.auther }}</div>
    <!--文章正文-->
    <div class="col-12">
      <!--在 article.body 后加上|safe 过滤器-->
      <p>{{ article.body|safe }}</p>
    </div>
  </div>
</div>

{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
            <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100'}}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <!-- <a href="#" class="btn btn-primary">阅读本文</a> -->
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title%} {% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入 monokai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %} {% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖jquery.js和popper.js 因此在这里引入-->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

templates/footer.html
{% load staticfiles %}

<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy;2020</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <!-- 导航栏商标-->
    <a class="navbar-brand" href="#">我的博客</a>

    <!-- 导航入口 -->
    <div>
        <ul class="navbar-nav">
            <!-- 条目 -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                <!--<a class="nav-link" href="#">文章</a> v-->
                <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
            </li>
        </ul>
    </div>

    </div>
</nav>